### ISSUE TITLE
BadMethodCallException in Blog Posts

### ISSUE THREAD

**Issue by szenadam** [vikijuhasz/blog-laravel-course#4]
After clicking on "Blog Posts":

https://i.imgur.com/2Wj89Kp.png

**Comment by vikijuhasz** [comment]
To fix this bug:
- Register to redislabs.com
- Add to the .env file:  
REDIS_HOST=endpoint provided on the redislabs page      		
REDIS_PASSWORD=password provided on the redislabs page  				
REDIS_CACHE_DB=cache    
REDIS_CACHE_DB=0   
CACHE_DRIVER=redis
